### ISSUE TITLE
HD16 won't login

### ISSUE THREAD

**Issue by Koreysherwin** [geoffsharris/Indigo-Rainmachine#2]
RainMachineDev Debug            Stopping device: RainMachine HD16
   RainMachineDev                  Device Stop Communication
   RainMachineDev Debug            Starting device: RainMachine HD16
   RainMachineDev                  device exists MAC: 50:3E:AA:41:CF:A8
   RainMachineDev                  Added Device id: 1342583430 to self.rainmachine_devices
   RainMachineDev                  Device Start Communication
   RainMachineDev Debug            Started device: 1342583430
   RainMachineDev Debug            address : 
batteryLevel : None
buttonGroupCount : 0
configured : True
description : 
deviceTypeId : RainMachineHD12
displayStateId : zoneNumber
displayStateImageSel : SensorTripped
displayStateValRaw : 
displayStateValUi : 
enabled : True
energyAccumBaseTime : None
energyAccumTimeDelta : None
energyAccumTotal : None
energyCurLevel : None
errorState : 
folderId : 917192953
globalProps : MetaProps : (dict)
     com.pluginfactory.indigoplugin.rainmachinedev : (dict)
          connectionType : Local (string)
          deviceMAC : 50:3E:AA:41:CF:A8 (string)
          https : false (bool)
          ip_address : 192.168.0.243 (string)
          password : xxxxxxxxxxx (string)
          port : 8080 (string)
          username :  (string)
id : 1342583430
lastChanged : 2020-12-16 21:59:14
lastSuccessfulComm : 2020-12-16 21:59:14
model : Rain Machine HD-12
name : RainMachine HD16
ownerProps : com.pluginfactory.indigoplugin.rainmachinedev : (dict)
     connectionType : Local (string)
     deviceMAC : 50:3E:AA:41:CF:A8 (string)
     https : false (bool)
     ip_address : 192.168.0.243 (string)
     password : xxxxxxxxx (string)
     port : 8080 (string)
     username :  (string)
pluginId : com.pluginfactory.indigoplugin.rainmachinedev
pluginProps : com.pluginfactory.indigoplugin.rainmachinedev : (dict)
     connectionType : Local (string)
     deviceMAC : 50:3E:AA:41:CF:A8 (string)
     https : false (bool)
     ip_address : 192.168.0.243 (string)
     password : xxxxxxxxxx (string)
     port : 8080 (string)
     username :  (string)
protocol : Plugin
remoteDisplay : True
sharedProps : com.indigodomo.indigoserver : (dict)
states : States : (dict)
     currentProgram :  (string)
     deviceIsOnline : off (on/off bool)
     deviceTimestamp :  (string)
     programMinutesLeft :  (string)
     zoneMinutesLeft :  (string)
     zoneNumber :  (string)
subModel : 
supportsAllLightsOnOff : False
supportsAllOff : False
supportsStatusRequest : False
version : None
   RainMachineDev                  Needs to login

**Comment by geoffsharris** [comment]
There is no corresponding login successful message as I had this in the debugger logs. Will fix that to make this clear. It was able to login as it got the MAC address from the device. Try and set up a schedule and in actions there should be a menu called rainmachine where you can set up the events to trigger.
