### ISSUE TITLE
Device State info not updated

### ISSUE THREAD

**Issue by Koreysherwin** [geoffsharris/Indigo-Rainmachine#3]
The State indicator shows  red and the Custom State info does not get updated.

These screenshots taken, while a zone is running via the plugin.

<img width="623" alt="Screen Shot 2020-12-17 at 10 16 35 AM" src="https://user-images.githubusercontent.com/51178437/102526748-ffe9b600-4050-11eb-98c7-9510775eca65.png">

<img width="361" alt="Screen Shot 2020-12-17 at 10 11 35 AM" src="https://user-images.githubusercontent.com/51178437/102526784-0aa44b00-4051-11eb-9157-013157b5d095.png">

**Comment by geoffsharris** [comment]
Added a new version to improve Server UI. Probably need to open any existing devices and resave or delete and create new ones. Same goes for triggers and schedules.

**Comment by Koreysherwin** [comment]
Nice work! all working quite well!
